#!/usr/bin/env python3
"""Generate main/include/f-ota-pubkey.h from the OTA manifest signing public key.

Usage: python tools/gen_pubkey_header.py <public-key.pem>

The private key lives on the release YubiKey (PIV slot 9c); only the public
key is ever committed. Re-run this ONLY on key rotation - the output header
is what every device in the field trusts.
"""
import subprocess
import sys
import textwrap
from pathlib import Path

HEADER = Path(__file__).resolve().parent.parent / "main" / "include" / "f-ota-pubkey.h"


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    pem = Path(sys.argv[1])

    der = subprocess.run(
        ["openssl", "ec", "-pubin", "-in", str(pem), "-outform", "DER"],
        capture_output=True, check=True,
    ).stdout
    # PSA (mbedTLS 4 / TF-PSA-Crypto on the device) imports EC public keys as
    # the raw uncompressed point 0x04||X||Y - the last 65 bytes of the SPKI.
    point = der[-65:]
    if len(der) != 91 or point[0] != 0x04:
        sys.exit("error: input does not look like a P-256 SubjectPublicKeyInfo")

    rows = textwrap.wrap(", ".join(f"0x{b:02x}" for b in point), 72)
    body = "\n".join(f"    {r}" for r in rows)
    HEADER.write_text(
        "/* OTA manifest signing public key (ECDSA P-256, uncompressed point\n"
        " * 0x04||X||Y as imported by PSA Crypto).\n"
        " * Generated by tools/gen_pubkey_header.py - do not edit by hand.\n"
        " * The matching private key lives on the release YubiKey (PIV slot 9c).\n"
        " */\n"
        "#pragma once\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n"
        "\n"
        "static const uint8_t OTA_MANIFEST_PUBKEY_P256[] = {\n"
        f"{body}\n"
        "};\n"
        f"static const size_t OTA_MANIFEST_PUBKEY_P256_LEN = sizeof(OTA_MANIFEST_PUBKEY_P256);\n",
        newline="\n",
    )
    print(f"wrote {HEADER} ({len(point)} bytes uncompressed point)")


if __name__ == "__main__":
    main()
